### ISSUE TITLE
Results and Analysis

### ISSUE THREAD

**Issue by ashacekar** [gray-stanton/spamGAN#3]
I was able to run spam_train.py successfully. I m not sure how to know accuracy, f1 score and perplexity. Though i see two result files here in .xls format but i m not sure how to make it for my data. Can i know to how to infer results here?

**Comment by bigheiniu** [comment]
Hello, I could not run the code. Some problems related to Texar version.
Could you tell me your Texar version ???
thx

**Comment by bigheiniu** [comment]
> Hello, I could not run the code. Some problems related to Texar version.
> Could you tell me your Texar version ???
> thx

I found the version is Texar v0.1.0

**Comment by ashacekar** [comment]
Hi bigheiniu,
My texar version is same. You just have to remove the parameter (Max_Length) from the specified file (rnn_decoder.py). You can see location of the file in error. Also u might need few more minor fixes further while execution.
